// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	api "github.com/lucassabreu/clockify-cli/api"
	cmdutil "github.com/lucassabreu/clockify-cli/pkg/cmdutil"

	dto "github.com/lucassabreu/clockify-cli/api/dto"

	mock "github.com/stretchr/testify/mock"
)

// MockFactory is an autogenerated mock type for the Factory type
type MockFactory struct {
	mock.Mock
}

// Client provides a mock function with given fields:
func (_m *MockFactory) Client() (api.Client, error) {
	ret := _m.Called()

	var r0 api.Client
	if rf, ok := ret.Get(0).(func() api.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.Client)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Config provides a mock function with given fields:
func (_m *MockFactory) Config() cmdutil.Config {
	ret := _m.Called()

	var r0 cmdutil.Config
	if rf, ok := ret.Get(0).(func() cmdutil.Config); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(cmdutil.Config)
		}
	}

	return r0
}

// GetUserID provides a mock function with given fields:
func (_m *MockFactory) GetUserID() (string, error) {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWorkspace provides a mock function with given fields:
func (_m *MockFactory) GetWorkspace() (dto.Workspace, error) {
	ret := _m.Called()

	var r0 dto.Workspace
	if rf, ok := ret.Get(0).(func() dto.Workspace); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(dto.Workspace)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWorkspaceID provides a mock function with given fields:
func (_m *MockFactory) GetWorkspaceID() (string, error) {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Version provides a mock function with given fields:
func (_m *MockFactory) Version() cmdutil.Version {
	ret := _m.Called()

	var r0 cmdutil.Version
	if rf, ok := ret.Get(0).(func() cmdutil.Version); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(cmdutil.Version)
	}

	return r0
}

type mockConstructorTestingTNewMockFactory interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockFactory creates a new instance of MockFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockFactory(t mockConstructorTestingTNewMockFactory) *MockFactory {
	mock := &MockFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
