version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    hooks:
      pre:
        - go mod download
    main: ./cmd/clockify-cli

archives:
  - id: default
    name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

snapcrafts:
  - name: clockify-cli
    summary: Helps to interact with Clockfy's API
    description: Helps to interact with Clockfy's API

    grade: stable
    publish: true
    confinement: strict

    apps:
      clockify-cli:
        plugs: ["network"]

homebrew_casks:
  - name: clockify-cli
    repository:
      owner: lucassabreu
      name: homebrew-tap
    homepage: https://github.com/lucassabreu/clockify-cli
    description: Helps to interact with Clockfy's API
