builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    hooks:
      pre:
        - go mod download

archives:
  - id: default
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: '{{ .Tag }}-next'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

snapcrafts:
  - name: clockify-cli
    summary: Helps to interact with Clockfy's API
    description: Helps to interact with Clockfy's API

    grade: stable
    publish: true

    apps:
      clockify-cli:
        plugs: ['network']

brews:
  - tap:
      owner: lucassabreu
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/lucassabreu/clockify-cli
    description: Helps to interact with Clockfy's API
    test: |
      system "#{bin}/clockify-cli version"
    dependencies:
