before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
archives:
  - id: default
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
snapcrafts:
  - name: clockify-cli
    publish: false
    summary: Helps to interact with Clockfy's API
    description: Helps to interact with Clockfy's API
    grade: stable
    confinement: strict
    apps:
      clockify-cli:
