#!/bin/sh

download() {
  curl -s https://api.github.com/repos/lucassabreu/clockify-cli/releases/latest | \
      grep 'browser_download_url.*clockify-cli_.*_Linux_x86_64.tar.gz' | \
      cut -d : -f 2- | tr -d \" | \
      wget -qi - -O- | tar zxf - clockify-cli
}

set -e
download

rm -rf site/content/commands/* || true
./clockify-cli gensite site/content/commands

# fix root command to be "chapter root"
mv site/content/commands/clockify-cli.md site/content/commands/_index.md

# add license information
mkdir -p site/content/license
echo '---
title: License
chapter: true
---
```txt' > site/content/license/_index.md
cat LICENSE >> site/content/license/_index.md
echo '```' >> site/content/license/_index.md

cd site && hugo
